### PR TITLE
Let's gamify development velocity

### PR DESCRIPTION
**Pull request by sungchun12**
resolves https://github.com/sungchun12/fst/issues/12

Use this to signal the developer is heading in the right vs. wrong direction.

Demo Video: https://www.loom.com/share/a511460186384e6691758cd6ef14b560

- [x] performance of queries in a line/bar chart vs. average performance
- [x]  number of modifications per file and average performance stats related to each file
- [x] last modified timestamps
- [x] update streamlit app for run on save to new data instead of polling
- [x] work on streamlit app to references a performance only duckdb database to avoid threadlocks
- [x] Toggle code snippet. Summary view of changes made so far at the bottom comparing bumber of modificafions and average performance for
- [x] Works with dbt build --store-failures and shows those results underneath the result preview.
- [x] Automatically starts and reruns streamlit with simple `fst start` command
- [x] Color code successes and failures in the bar charts and add average number of failures and successes to the bottom dataframe
- [x] trim the selection box to only the file name. 
- [x] Add ad hoc query runner to investigate failures

Out of Scope:
- [ ] How to display materialization type?
- [ ] Rerun streamlit app after the dynamic query handler finishes running

### CODE REVIEW

**Comment by sungchun12** [comment]
update streamlit app for run on save to new data instead of polling

**Comment by sungchun12** [comment]
Toggle code snippet. Summary view of changes made so far at the bottom comparing bumber of modificafions and average performance for

**Comment by sungchun12** [comment]
Works with `dbt build --store-failures` and shows those results underneath the result preview.

**Comment by sungchun12** [comment]
I recommend testing this on your machine in a living, breathing dbt project and see how it feels. Less concerned with code correctness and more with problems addressed, feelings felt, thoughts racing through your inner dialogue, and if you're in flow

**Comment by xtomflo** [comment]
Sadly I don't have access to any living, breathing dbt projects at the moment. Do you maybe know of an extended sample project I could get my hands on for proper testing like this? 🤔 @sungchun12

**Pull request merged**
